#!/usr/bin/env bash
# prints "Best School" 8 times

# Initialize i
i=1
# Declare loop
while [[ $i -le 10 ]];
      do
      if [ $i -eq 4 ]
      then
	  echo "bad luck"

      elif [ $i -eq 8 ]
      then
	  echo "good luck"
      else
	  echo "Best School"
      fi
      ((i++))
      
done
