#!/usr/bin/env bash

# Initialize the counter
i=1
# Declare an infinite loop
while :
do
	echo "Best School"
	if [ $i == 3 ]
	then
		echo "bad luck"
	elif [ $i == 6 ]
	then
		echo "good luck"
	elif [ $i == 8 ]
	then
		exit 0
	fi

	((i++))
done
