#!/usr/bin/env bash
# prints superstitious numbers, display phrase after 4th, 9th, 17th position
#initialize i
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((++i))
done
