#!/usr/bin/env bash
# displays hours from 0 - 12 and 1 - 59 minutes
hour=0
while [[ $hour -le 12 ]];
	do
	echo "Hour: "$hour
	min=1
	while [[ $min -le 59 ]];
		do
		echo $min
		((min++))
	done
	((hour++))
done
